export class BsoinModel {
  
        cod_soc!: string
        mat_pers!: string
        num_soins!: number
        dat_soins!: string
        npers!: string
        cod_etablis: any
        num_bord_etablis: any
        num_bord!: number
        annee_envoi!: number
        num_fam_bult!: number
        num_ass!: string
        cod_prestataire: any
        typ_parent!: string
        date_recp: any
        etat_bult!: string
        observ: any
        nature_bs!: string
        dat_avance_agent: any
        dat_avance_etablis: any
        mode_avanc_agent: any
        mode_avanc_etablis: any
        mnt_avance_agent: any
        mnt_avance_etablis: any
        dat_entree_etablis: any
        dat_sortie_etablis: any
        valide: any
        dat_valide: any
        tot_honor!: number
        tot_net!: number
        nbr_pieces: any
        num_ass_conj: any
        mat_pers_conj: any
        mode_remb: any
        dat_saisie!: string
        p_charge: any
        dat_p_charge: any
        num_p_charge: any
        nbr_jours: any
        num_piece: any
        mode_pay: any
        annee_bord: any
        num_bord_assur: any
        etat_avance_agent: any
        etat_avance_conj: any
        dat_avance_conj: any
        mnt_avance_conj: any
        typ_bult: any
        tot_honor_star: any
        tot_net_star: any
        tot_mnt_etablis: any
        mnt_caa: any
        mod_remb_recup: any
        mod_pay_av_agent: any
        obs_avance_agent: any
        obs_avance_etablis: any
        lib_bord_pc: any
        id_bord_pc: any
        etat_avance_etablis: any
        num_resume_agent: any
        num_resume_etablis: any
        cod_motif: any
        mat_agent: any
        docteur: any
        cod_user: any
        cod_serv: any
        cod_dept: any
        annee_pec: any
        id_bult_soin: any
        ligBult!: LigBult[]
      }
      
      export class LigBult {
        num_lig!: number
        type_act!: number
        abrv_act!: string
        cod_trait: any
        cod_mld: any
        num_ass: any
        cod_prestataire: any
        dat_acte!: string
        tot_honor!: number
        tot_net!: number
        indice_propos: any
        indice: any
        mld: any
        mnt_rembourse: any
        nbr_piece: any
        obs_lig_bult: any
        num_dent_lim1: any
        pos_dent_lim1: any
        num_dent_lim2: any
        pos_dent_lim2: any
        mode_remb: any
        num_ass_conj: any
        mat_pers_conj: any
        typ_praticien: any
        abrv_act_acc: any
        tot_net_conj: any
        typ_trait: any
        nbr_vign: any
        num_fam_bult!: number
        typ_parent: any
        dat_rembourse: any
        annee_bord: any
        num_bord_assur: any
        etat_avanc_etablis: any
        mnt_eng_star: any
        indice__star: any
        tot_honor_star: any
        tot_net_star: any
        abrv_act_star: any
        num_av_etablis: any
        num_bord_etablis: any
        cod_etablis: any
        cod_user: any
        tot_remb_comp: any
        tot_honor_comp: any
        mnt_etab_conv: any
        id_lig_bult: any
      }
      
